// Hand-drawn 16×16 sprites. One character = one pixel; "." is transparent.
// All artwork is original to AdamOS.

export const PALETTE: Record<string, string | undefined> = {
  ".": undefined,
  k: "#000000", // outline
  w: "#ffffff",
  g: "#c0c0c0",
  d: "#808080",
  y: "#ffd84a", // folder / gold
  o: "#c08a1e", // folder shade / wood
  b: "#000080", // navy
  c: "#2ea8d8", // sky
  t: "#008080", // brand teal
  a: "#f0a000", // brand accent
  n: "#1f9d3a", // green
  r: "#c81e1e", // red
  s: "#f2c79a", // skin
};

const computer = [
  "................",
  ".kkkkkkkkkkkkkk.",
  ".kwwwwwwwwwwwdk.",
  ".kwkkkkkkkkkgdk.",
  ".kwkccccccckgdk.",
  ".kwkccccccckgdk.",
  ".kwktccccttkgdk.",
  ".kwkttttttnkgdk.",
  ".kwkkkkkkkkkgdk.",
  ".kgggggggggggdk.",
  ".kddddddddddddk.",
  "..kkkkkkkkkkkk..",
  "....kgggggggk...",
  "...kwwwwwwwwdk..",
  "...kddddddddddk.",
  "...kkkkkkkkkkkk.",
];

export const ICONS = {
  computer,
  display: [
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kwwwwwwwwwwwdk.",
    ".kwkkkkkkkkkgdk.",
    ".kwkccccccakgdk.",
    ".kwkccccccckgdk.",
    ".kwkcnncccckgdk.",
    ".kwknnnnnnnkgdk.",
    ".kwkkkkkkkkkgdk.",
    ".kgggggggggggdk.",
    ".kddddddddddddk.",
    "..kkkkkkkkkkkk..",
    "....kgggggggk...",
    "...kwwwwwwwwdk..",
    "...kddddddddddk.",
    "...kkkkkkkkkkkk.",
  ],
  folder: [
    "................",
    "................",
    "..kkkkk.........",
    ".kwyyyyk........",
    "kwyyyyyykkkkkkk.",
    "kwyyyyyyyyyyyyok",
    "kwyyyyyyyyyyyyok",
    "kwyyyyyyyyyyyyok",
    "kwyyyyyyyyyyyyok",
    "kwyyyyyyyyyyyyok",
    "kwyyyyyyyyyyyyok",
    "kwyyyyyyyyyyyyok",
    "kwyyyyyyyyyyyyok",
    "kooooooooooooook",
    ".kkkkkkkkkkkkkk.",
    "................",
  ],
  briefcase: [
    "................",
    "................",
    "................",
    ".....kkkkkk.....",
    "....k......k....",
    ".kkkkkkkkkkkkkkk",
    ".koooooooooooook",
    ".koooooooooooook",
    ".kkkkkkyykkkkkkk",
    ".koooooyyooooook",
    ".koooooooooooook",
    ".koooooooooooook",
    ".koooooooooooook",
    ".kkkkkkkkkkkkkkk",
    "................",
    "................",
  ],
  trophy: [
    "................",
    "...kkkkkkkkkk...",
    ".kkkywyyyyyykkk.",
    "k..kywyyyyyyk..k",
    "k..kywyyyyyyk..k",
    ".k.kywyyyyyyk.k.",
    "..kkyyyyyyyykk..",
    "....kyyyyyyk....",
    ".....kyyyyk.....",
    "......kyyk......",
    "......kook......",
    ".....kooook.....",
    "....kkkkkkkk....",
    "....kddddddk....",
    "....kkkkkkkk....",
    "................",
  ],
  pdf: [
    "..kkkkkkkkk.....",
    "..kwwwwwwwkk....",
    "..kwwwwwwwkwk...",
    "..kwwwwwwwkkkk..",
    "..kwwwwwwwwwwk..",
    "..kwddddddddwk..",
    "..kwwwwwwwwwwk..",
    "..kwddddddddwk..",
    "..krrrrrrrrrrk..",
    "..krwwrwwrwwrk..",
    "..krrrrrrrrrrk..",
    "..kwwwwwwwwwwk..",
    "..kwddddddwwwk..",
    "..kwwwwwwwwwwk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  notepad: [
    "...k.k.k.k.k....",
    "..kkkkkkkkkkkk..",
    "..kwwwwwwwwwwk..",
    "..kwbbbbbbbbwk..",
    "..kwwwwwwwwwwk..",
    "..kwbbbbbbwwwk..",
    "..kwwwwwwwwwwk..",
    "..kwbbbbbbbbwk..",
    "..kwwwwwwwwwwk..",
    "..kwbbbbbwwwwk..",
    "..kwwwwwwwwwwk..",
    "..kwbbbbbbbbwk..",
    "..kwwwwwwwwwwk..",
    "..kwwwwwwwwwwk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  mail: [
    "................",
    "................",
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kwkwwwwwwwwkwk.",
    ".kwwkwwwwwwkwwk.",
    ".kwwwkwwwwkwwwk.",
    ".kwwwwkwwkwwwwk.",
    ".kwwwwwkkwwwwwk.",
    ".kwwwwwwwwwrrwk.",
    ".kwwwwwwwwwrrwk.",
    ".kwwwwwwwwwwwwk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
  ],
  recycle: [
    "................",
    ".....kkkkkk.....",
    "..kkkddddddkkk..",
    ".kggggggggggggk.",
    "..kkkkkkkkkkkk..",
    "..kgdgdgdgdgdk..",
    "..kgdgdgdgdgdk..",
    "...kgdgdgdgdk...",
    "...kgdnnngdgk...",
    "...kgnngnngdk...",
    "...kgdnnngdgk...",
    "...kgdgdgdgdk...",
    "....kgdgdgdk....",
    "....kkkkkkkk....",
    "................",
    "................",
  ],
  recycleFull: [
    "................",
    "....kk.kkk......",
    "...kwwkwwwk.....",
    ".kkkwwwkwwkkkk..",
    ".kggggggggggggk.",
    "..kkkkkkkkkkkk..",
    "..kgdgdgdgdgdk..",
    "...kgdgdgdgdk...",
    "...kgdnnngdgk...",
    "...kgnngnngdk...",
    "...kgdnnngdgk...",
    "...kgdgdgdgdk...",
    "....kgdgdgdk....",
    "....kkkkkkkk....",
    "................",
    "................",
  ],
  people: [
    "................",
    "................",
    "...kkk....kkk...",
    "..ksssk..ksssk..",
    "..ksssk..ksssk..",
    "...kkk....kkk...",
    "..kbbbk..knnnk..",
    ".kbbbbbkknnnnnk.",
    ".kbbbbbkknnnnnk.",
    ".kbbbbbkknnnnnk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  globe: [
    "................",
    "................",
    ".....kkkkkk.....",
    "...kkcccnnckk...",
    "..kcccnnnnccck..",
    ".kccccnnnccccck.",
    ".kccccnncccccck.",
    ".knncccccccnnck.",
    ".knnncccccnnnck.",
    ".kcnnccccccnnck.",
    ".kcccccccccccck.",
    "..kccccnnnccck..",
    "...kkcccccckk...",
    ".....kkkkkk.....",
    "................",
    "................",
  ],
  logo: [
    "................",
    "................",
    "......kkkk......",
    ".....kttttk.....",
    "....kttkkttk....",
    "....ktk..ktk....",
    "...kttk..kttk...",
    "...kttkkkkttk...",
    "..kttttttttttk..",
    "..kttkkkkkkttk..",
    ".kttk......kttk.",
    ".kkkk......kkkk.",
    "................",
    ".kaaaaaaaaaaaak.",
    ".kkkkkkkkkkkkkk.",
    "................",
  ],
  info: [
    "................",
    ".....kkkkkk.....",
    "...kkcccccckk...",
    "..kccccwwcccck..",
    "..kccccwwcccck..",
    ".kcccccccccccck.",
    ".kccccwwwccccck.",
    ".kcccccwwccccck.",
    ".kcccccwwccccck.",
    ".kcccccwwccccck.",
    "..kccccwwcccck..",
    "..kcccwwwwccck..",
    "...kkcccccckk...",
    ".....kkkkkk.....",
    "................",
    "................",
  ],
  power: [
    "................",
    "................",
    ".......kk.......",
    "....kk.rr.kk....",
    "...krk.rr.krk...",
    "..krk..rr..krk..",
    "..kr...rr...rk..",
    ".kr....rr....rk.",
    ".kr....kk....rk.",
    ".kr..........rk.",
    "..kr........rk..",
    "..krk......krk..",
    "...krrkkkkrrk...",
    ".....krrrrk.....",
    "................",
    "................",
  ],
} satisfies Record<string, string[]>;

export type IconName = keyof typeof ICONS;
